version: '3.7'
services:
  redis:
    restart: 'on-failure'
    image: 'bitnami/redis:latest'
    env_file:
      - ./.env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_AOF_ENABLED=no
    command: /opt/bitnami/scripts/redis/run.sh
    networks:
      - etl

  elasticsearch:
    image: elasticsearch:8.4.1
    env_file:
      - ./.env
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    depends_on:
      - redis
    networks:
      - etl

  fastapi:
    build:
      context: ./src/
    expose:
      - "8000"
    depends_on:
      - redis
      - elasticsearch
    networks:
      - etl

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
    depends_on:
      - redis
      - elasticsearch
    networks:
      - etl

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - etl

networks:
  etl:
    driver: bridge

volumes:
  elastic_data:
  static_volume: